apiVersion: v1
kind: Service
metadata:
  namespace: devsupport
  name: joke-service
  labels:
    app: joke-service
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.0.1
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: joke-service
