spring:
  application:
    name:ws-tripsy-api

logging:
  level:
    org.springframework.security: trace
    
    
    

    
    
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/auth/validate
#          #jwk-set-uri: http://localhost:8090/auth/validate